<?php

namespace App\Support;

use App\Models\Service;
use App\Services\UkPostcodeLookup;

class ServiceMapLink
{
    public static function generate(Service $service): string
    {
        if ($service->latitude !== null && $service->longitude !== null) {
            return 'https://www.google.com/maps?q='.rawurlencode("{$service->latitude},{$service->longitude}");
        }

        $address = $service->formattedAddress();

        if ($address !== '') {
            return 'https://www.google.com/maps?q='.rawurlencode($address);
        }

        if (filled($service->location)) {
            return 'https://www.google.com/maps?q='.rawurlencode(trim((string) $service->location).', UK');
        }

        return '';
    }

    public static function syncCoordinates(Service $service): void
    {
        if (! filled($service->postcode)) {
            return;
        }

        $coordinates = app(UkPostcodeLookup::class)->coordinates((string) $service->postcode);

        if ($coordinates === null) {
            return;
        }

        $service->latitude = $coordinates['latitude'];
        $service->longitude = $coordinates['longitude'];
    }

    public static function syncMapLink(Service $service): void
    {
        $generated = self::generate($service);

        if ($generated === '') {
            return;
        }

        if (blank($service->map_link)) {
            $service->map_link = $generated;

            return;
        }

        $current = strtolower(trim((string) $service->map_link));
        $looksAutoGenerated = str_contains($current, 'google.com/maps')
            || str_contains($current, 'maps.google.com');

        if ($looksAutoGenerated) {
            $service->map_link = $generated;
        }
    }

    public static function embedUrl(?float $latitude, ?float $longitude): ?string
    {
        if ($latitude === null || $longitude === null) {
            return null;
        }

        $delta = 0.01;
        $left = $longitude - $delta;
        $right = $longitude + $delta;
        $top = $latitude + $delta;
        $bottom = $latitude - $delta;

        return 'https://www.openstreetmap.org/export/embed.html?bbox='
            .rawurlencode("{$left},{$bottom},{$right},{$top}")
            .'&layer=mapnik&marker='.rawurlencode("{$latitude},{$longitude}");
    }
}
